/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Delivery;
import Models.MessageManager;
import Models.Order;
import Models.OrderLine;
import Models.OrderManager;
import Models.PaymentManager;
import Models.Product;
import Models.ProductManager;
import Models.User;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author lucal
 */
public class Checkout extends javax.swing.JFrame {

    //current User
    User loadedUser;
    //current order
    Order loadedBasket;
    
    //last frame before the basket
    String previousBasketFrame;
    
    Delivery loadedDelivery;
    
    Product loadedProduct;
    
    /**
     * Creates new form Checkout
     */
    public Checkout(User user, Order order, String lastBasketFrame,Product product, Delivery delivery) {
        initComponents();
        
        loadedUser = user;
        loadedBasket = order;
        previousBasketFrame = lastBasketFrame;
        loadedDelivery = delivery;
        loadedProduct = product;
        for (Map.Entry<Integer,OrderLine> entry : loadedBasket.getOrderLines().entrySet()) 
        {
            OrderLine oL = entry.getValue();
            txtOrderSummary.setText(txtOrderSummary.getText() + "\n" + oL.getQuantity() + " X " + oL.getProduct().getName());
            
        }
        
        lblOrderTotal.setText("Order Tolal: £" + loadedBasket.CalculateOrderTotal());
        
        if(delivery != null)
        {
            cmboOrderType.setSelectedIndex(2);
        }
        else 
        {
            btnEditDelivery.setVisible(false);
            loadedDelivery = new Delivery();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner2 = new javax.swing.JPanel();
        lblCheckout = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblOrderTotal = new javax.swing.JLabel();
        lblDeliveryPrice = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblOrderSummary = new javax.swing.JLabel();
        cmboOrderType = new javax.swing.JComboBox<>();
        cmboPaymentType = new javax.swing.JComboBox<>();
        btnMakePayment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrderSummary = new javax.swing.JTextArea();
        btnEditDelivery = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBanner2.setBackground(new java.awt.Color(51, 204, 255));
        pnlBanner2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        pnlBanner2.setForeground(new java.awt.Color(102, 204, 255));
        pnlBanner2.setToolTipText("");

        lblCheckout.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCheckout.setText("Checkout");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner2Layout = new javax.swing.GroupLayout(pnlBanner2);
        pnlBanner2.setLayout(pnlBanner2Layout);
        pnlBanner2Layout.setHorizontalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCheckout)
                .addGap(59, 59, 59)
                .addComponent(btnBack)
                .addGap(39, 39, 39))
        );
        pnlBanner2Layout.setVerticalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBanner2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckout)
                    .addComponent(btnBack))
                .addGap(19, 19, 19))
        );

        lblOrderTotal.setText("Order Total");

        lblDeliveryPrice.setText("Delivery Price");

        lblTotal.setText("Total");

        lblOrderSummary.setText("Order Summary");

        cmboOrderType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order Type", "Collect", "Delivery" }));
        cmboOrderType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboOrderTypeActionPerformed(evt);
            }
        });

        cmboPaymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Payment Type", "Cash", "Invoice", "Debit/Credit" }));
        cmboPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboPaymentTypeActionPerformed(evt);
            }
        });

        btnMakePayment.setText("Make Payment");
        btnMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePaymentActionPerformed(evt);
            }
        });

        txtOrderSummary.setEditable(false);
        txtOrderSummary.setColumns(20);
        txtOrderSummary.setRows(5);
        jScrollPane1.setViewportView(txtOrderSummary);

        btnEditDelivery.setText("Edit Delivery");
        btnEditDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDeliveryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBanner2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnEditDelivery)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnMakePayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmboOrderType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmboPaymentType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(85, 85, 85))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrderTotal)
                                    .addComponent(lblDeliveryPrice)
                                    .addComponent(lblTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderSummary)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBanner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderTotal)
                    .addComponent(lblOrderSummary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDeliveryPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmboOrderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmboPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMakePayment))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditDelivery)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        Basket basket = new Basket(loadedUser, loadedBasket, previousBasketFrame, loadedProduct);
        basket.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmboPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboPaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboPaymentTypeActionPerformed

    private void cmboOrderTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboOrderTypeActionPerformed
        // TODO add your handling code here:
        
        if(cmboOrderType.getSelectedItem().toString().equals("Delivery") && loadedDelivery == null)
        {
            DeliveryInfo deliveryInfo = new DeliveryInfo(loadedUser, loadedBasket,previousBasketFrame,loadedProduct, loadedDelivery);
            deliveryInfo.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_cmboOrderTypeActionPerformed

    private void btnEditDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDeliveryActionPerformed
        // TODO add your handling code here:
        
        DeliveryInfo deliveryInfo = new DeliveryInfo(loadedUser, loadedBasket,previousBasketFrame,loadedProduct, loadedDelivery);
        deliveryInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditDeliveryActionPerformed

    private void btnMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePaymentActionPerformed
        // TODO add your handling code here:
        if(cmboPaymentType.getSelectedItem().toString().equals("Debit/Credit"))
        {
            //creates new paymentmanager
            PaymentManager paymentManager = new PaymentManager();
           //makes payment using order price as input. adds an additional 10 if the order is a delivery
            boolean paymentSuccessful = paymentManager.TryMakePayment(loadedBasket.CalculateOrderTotal() + (loadedDelivery.getAddress().getPostCode().equals("") ? 0 : 10));
            if(!paymentSuccessful){
                JOptionPane.showMessageDialog(null, "Payment Uncsuccessful");
                return;
            }
            //makes new order manager
            OrderManager oManager = new OrderManager();
            //makes new product manager
            ProductManager pManager = new ProductManager();
            
            
            //registers delivery and sets loadeddelivery to registered delivery
            loadedDelivery = oManager.RegisterDelivery(loadedDelivery);
            
            //updates stock level using the  hashmap of orderlines of the basket as input
            pManager.UpdateStockLevel(loadedBasket.getOrderLines());
            //creates an option panel and displays a thank you message
            JOptionPane.showMessageDialog(null, "Thank You For Your Purchase");
            
            //creates new message manager
            MessageManager mManager = new MessageManager();
            //sends a new email confirming the purchase
            String email = "Thank you " + loadedUser.getFirstName() + " " + loadedUser.getSurname() + " for your purchase as maxiCycles \n Here Is a summary of your purchase: \n \n";
            
            //checks if the order has a postcode to detirmine if it is a delivery
            if(!loadedDelivery.getAddress().getPostCode().equals(""))
            {
                //adds delivery information to the email
                email += "DeliveryId: " + loadedDelivery.getDeliveryId() + "\n";
                email += "DeliveryType: " + loadedDelivery.getType() + "\n";
                email += "Address: " + loadedDelivery.getAddress().getStreet() + "\n" + loadedDelivery.getAddress().getTown() + "\n" + loadedDelivery.getAddress().getCity()+ "\n" + loadedDelivery.getAddress().getCountry()+ "\n" + loadedDelivery.getAddress().getPostCode() + "\n \n";
            }
            
            //adds order information to the email
            email += "OrderId: " + loadedDelivery.getOrder().getOrderId() +"\n";

            //loops through orderlines and adds a summary for each in the email
            for (Map.Entry<Integer, OrderLine> entry : loadedBasket.getOrderLines().entrySet()) {
                OrderLine oL = entry.getValue();
                
                email += oL.getQuantity() + " X " + oL.getProduct().getName() + "  £" + oL.getProduct().getPrice() + "\n";
                
            }
            //sends email
            mManager.sendEmail(loadedUser.getEmailAddress(), "Purchase Confirmation", email);
            
            HomePage homePage = new HomePage(loadedUser, null);
            homePage.setVisible(true);
            this.dispose();
        }
        else
        {
            PaymentPage paymentPage = new PaymentPage(loadedUser, loadedBasket, previousBasketFrame, loadedProduct, loadedDelivery);
            paymentPage.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnMakePaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditDelivery;
    private javax.swing.JButton btnMakePayment;
    private javax.swing.JComboBox<String> cmboOrderType;
    private javax.swing.JComboBox<String> cmboPaymentType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheckout;
    private javax.swing.JLabel lblDeliveryPrice;
    private javax.swing.JLabel lblOrderSummary;
    private javax.swing.JLabel lblOrderTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBanner2;
    private javax.swing.JTextArea txtOrderSummary;
    // End of variables declaration//GEN-END:variables
}
