/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Address;
import Models.Delivery;
import Models.Order;
import Models.OrderLine;
import Models.OrderManager;
import Models.Product;
import Models.User;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucal
 */
public class CustomerOrders extends javax.swing.JFrame {

    //current User
    User loadedUser;
    //current order
    Order loadedBasket;
    /**
     * Creates new form CustomerOrders
     */
    public CustomerOrders(User user, Order order) {
        initComponents();
        
        loadedBasket = order;
        loadedUser = user;
        OrderManager oManager = new OrderManager();
        
        HashMap<Integer,Delivery> deliveries = oManager.LoadDeliveries();
        
        DefaultTableModel basketTableModel = (DefaultTableModel) tblCustomerOrders.getModel();
        
        
        for(Map.Entry<Integer, Delivery> entry : deliveries.entrySet())
        {
            if(entry.getValue().getOrder().getCustomer().getUserName().equals(loadedUser.getUserName())){
                String summary = "";
            
                //loops through orderlines
                for (Map.Entry<Integer, OrderLine> oL : entry.getValue().getOrder().getOrderLines().entrySet()) 
                {
                    Product product = oL.getValue().getProduct();
                
                    summary += oL.getValue().getQuantity() + " X " + product.getName() + "\n" ;
                }
            
                Delivery actualDelivery = entry.getValue();
            
                Address address = actualDelivery.getAddress();
            
                String addressString = address.getStreet() + "\n" + address.getTown() + "\n" + address.getCity() + "\n" + address.getCountry() + "\n" + address.getPostCode();
            
            
                Order orderInDelivery = actualDelivery.getOrder();
                //adds rows to table model
                basketTableModel.addRow(new Object[]{
                   orderInDelivery.getOrderId(),
                    "£" + orderInDelivery.getPrice(),
                    actualDelivery.getStatus().toString(),
                    "Delivery",
                    actualDelivery.getPredictedDeliveryDate(),
                    summary,
                    actualDelivery.getType().toString(),
                   addressString
                
                
                });
            
            }
            
            
            
            
        }
        
        tblCustomerOrders.setModel(basketTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner2 = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerOrders = new javax.swing.JTable();
        btnPrintReturnForm = new javax.swing.JButton();
        btnRequestRefund = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBanner2.setBackground(new java.awt.Color(51, 204, 255));
        pnlBanner2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        pnlBanner2.setForeground(new java.awt.Color(102, 204, 255));
        pnlBanner2.setToolTipText("");

        lblProfile.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblProfile.setText("Orders");

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner2Layout = new javax.swing.GroupLayout(pnlBanner2);
        pnlBanner2.setLayout(pnlBanner2Layout);
        pnlBanner2Layout.setHorizontalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner2Layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(lblProfile)
                .addGap(311, 311, 311)
                .addComponent(btnBack1)
                .addContainerGap())
        );
        pnlBanner2Layout.setVerticalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack1)
                    .addComponent(lblProfile))
                .addGap(19, 19, 19))
        );

        tblCustomerOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Price", "Status", "OrderType", "Predicted Delivery Date", "Summary", "Delivery Type", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerOrders);

        btnPrintReturnForm.setText("Print Return Form");
        btnPrintReturnForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReturnFormActionPerformed(evt);
            }
        });

        btnRequestRefund.setText("Request Refund");

        lblQuantity.setText("Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPrintReturnForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRequestRefund))
                    .addComponent(pnlBanner2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblQuantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBanner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrintReturnForm)
                    .addComponent(btnRequestRefund))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:

        CustomerProfile customerProfile = new CustomerProfile(loadedUser, loadedBasket);
        customerProfile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnPrintReturnFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReturnFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintReturnFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnPrintReturnForm;
    private javax.swing.JButton btnRequestRefund;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JPanel pnlBanner2;
    private javax.swing.JTable tblCustomerOrders;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
