/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Order;
import Models.Role;
import Models.User;
import Models.UserManager;
import java.awt.Component;
import static java.lang.reflect.Array.set;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;

/**
 *
 * @author lucal
 */
public class Dashboard extends javax.swing.JFrame {

    
    User loadedUser;
    Order loadedBasket;
    /**
     * Creates new form Dashboard
     */
    public Dashboard(User user, Order order) {
        initComponents();
        UserManager uManager = new UserManager();
        loadedBasket = order;
        loadedUser = user;
        //hides all buttons
        HideAllButtons();
        switch (user.getRole().getRoleName()) {
            case "Admin":
                btnRegisterStaff.setVisible(true);
                break;
            default:
                throw new AssertionError();
       }
    }
    
    public void HideAllButtons()
    {
        for (Component comp : pnlDashboard.getComponents() ) 
        {
            if(comp instanceof JButton)
            {
               ((JButton) comp).setVisible(false);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner2 = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        pnlDashboard = new javax.swing.JPanel();
        btnRegisterStaff = new javax.swing.JButton();
        btnViewAllOrders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBanner2.setBackground(new java.awt.Color(51, 204, 255));
        pnlBanner2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        pnlBanner2.setForeground(new java.awt.Color(102, 204, 255));
        pnlBanner2.setToolTipText("");

        lblDashboard.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDashboard.setText("Dashboard");

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner2Layout = new javax.swing.GroupLayout(pnlBanner2);
        pnlBanner2.setLayout(pnlBanner2Layout);
        pnlBanner2Layout.setHorizontalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner2Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(lblDashboard)
                .addGap(74, 74, 74)
                .addComponent(btnBack1)
                .addContainerGap())
        );
        pnlBanner2Layout.setVerticalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack1)
                    .addComponent(lblDashboard))
                .addGap(19, 19, 19))
        );

        btnRegisterStaff.setText("Register Staff");
        btnRegisterStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterStaffActionPerformed(evt);
            }
        });

        btnViewAllOrders.setText("View All Orders");
        btnViewAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisterStaff)
                    .addComponent(btnViewAllOrders))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegisterStaff)
                .addGap(18, 18, 18)
                .addComponent(btnViewAllOrders)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBanner2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBanner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:

        StaffProfile staffProfile = new StaffProfile(loadedUser, loadedBasket);
        staffProfile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnRegisterStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterStaffActionPerformed
        // TODO add your handling code here:
        RegisterStaff registerStaff = new RegisterStaff(loadedUser,loadedBasket);
        registerStaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterStaffActionPerformed

    private void btnViewAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllOrdersActionPerformed
        // TODO add your handling code here:
        AllOrders allOrders = new AllOrders(loadedUser,loadedBasket);
        allOrders.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewAllOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnRegisterStaff;
    private javax.swing.JButton btnViewAllOrders;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JPanel pnlBanner2;
    private javax.swing.JPanel pnlDashboard;
    // End of variables declaration//GEN-END:variables
}
