/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Address;
import Models.CourierCompany;
import Models.Delivery;
import Models.Order;
import Models.Product;
import Models.User;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author lucal
 */
public class DeliveryInfo extends javax.swing.JFrame {

    
    //current User
    User loadedUser;
    //current order
    Order loadedBasket;
    
    //last frame before the basket
    String previousBasketFrame;
    
    //current Delivery
    Delivery loadedDelivery;
    
    Product loadedProduct;
    
    /**
     * Creates new form DeliveryInfo
     */
    public DeliveryInfo(User user, Order order, String lastBasketFrame, Product product, Delivery delivery) {
        initComponents();
        loadedUser = user;
        loadedBasket = order;
        previousBasketFrame = lastBasketFrame;
        loadedDelivery = delivery;
        loadedProduct = product;
        
        if(delivery != null)
        {
            txtStreet.setText(delivery.getAddress().getStreet());
            txtTown.setText(delivery.getAddress().getTown());
            txtCity.setText(delivery.getAddress().getCity());
            txtCountry.setText(delivery.getAddress().getCountry());
            txtPostCode.setText(delivery.getAddress().getPostCode());
            
            switch (delivery.getType()) {
                case Delivery.DeliveryType.firstClass:
                    cmboDeliveryType.setSelectedIndex(1);
                    break;
                case Delivery.DeliveryType.secondClass:
                    cmboDeliveryType.setSelectedIndex(2);
                    break;
                case Delivery.DeliveryType.courier:
                    cmboDeliveryType.setSelectedIndex(3);
                    break;
                default:
                    throw new AssertionError();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner2 = new javax.swing.JPanel();
        lblCheckout = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblStreet = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        lblTown = new javax.swing.JLabel();
        txtTown = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        lblPostCode = new javax.swing.JLabel();
        txtPostCode = new javax.swing.JTextField();
        cmboDeliveryType = new javax.swing.JComboBox<>();
        cmboCourierCompany = new javax.swing.JComboBox<>();
        lblEstimatedDeliveryTime = new javax.swing.JLabel();
        btnUsePreferredAddress = new javax.swing.JButton();
        btnUseUserAddress = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBanner2.setBackground(new java.awt.Color(51, 204, 255));
        pnlBanner2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        pnlBanner2.setForeground(new java.awt.Color(102, 204, 255));
        pnlBanner2.setToolTipText("");

        lblCheckout.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCheckout.setText("Delivery");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner2Layout = new javax.swing.GroupLayout(pnlBanner2);
        pnlBanner2.setLayout(pnlBanner2Layout);
        pnlBanner2Layout.setHorizontalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCheckout)
                .addGap(59, 59, 59)
                .addComponent(btnBack)
                .addGap(39, 39, 39))
        );
        pnlBanner2Layout.setVerticalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBanner2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckout)
                    .addComponent(btnBack))
                .addGap(19, 19, 19))
        );

        lblStreet.setText("Street");

        lblTown.setText("Town");

        lblCity.setText("City");

        lblCountry.setText("Country");

        lblPostCode.setText("PostCode");

        cmboDeliveryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery Type", "1st Class", "2nd Class", "Courier Delivery" }));

        cmboCourierCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Courier Company", "Caledonian Couriers", "Eagle Couriers" }));

        lblEstimatedDeliveryTime.setText("Estimated Delivery Time");

        btnUsePreferredAddress.setText("Use Preferred Address");

        btnUseUserAddress.setText("Use User Address");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBanner2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmboDeliveryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmboCourierCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUsePreferredAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStreet)
                                    .addComponent(lblTown)
                                    .addComponent(lblCity)
                                    .addComponent(lblCountry)
                                    .addComponent(lblPostCode))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtTown, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblEstimatedDeliveryTime)
                            .addComponent(btnUseUserAddress))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBanner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPostCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmboDeliveryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmboCourierCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstimatedDeliveryTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsePreferredAddress)
                    .addComponent(btnSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUseUserAddress)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        Checkout checkout = new Checkout(loadedUser, loadedBasket, previousBasketFrame,loadedProduct, null);
        checkout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String street = txtStreet.getText();
        String town = txtTown.getText();
        String city = txtCity.getText();
        String country = txtCountry.getText();
        String postCode = txtPostCode.getText();
        
        Delivery.DeliveryType deliveryType;
        String type = cmboDeliveryType.getSelectedItem().toString();
        
        switch (type) {
            case "1st Class":
                deliveryType = Delivery.DeliveryType.firstClass;
                break;
            case "2nd Class":
                deliveryType = Delivery.DeliveryType.secondClass;
                break;
            case "Courier":
                deliveryType = Delivery.DeliveryType.courier;
                break;
            default:
                throw new AssertionError();
        }
        
        Date deliveryDate = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(deliveryDate);
        cal.add(Calendar.DATE, 5);
        deliveryDate = cal.getTime();
        
        //public Address(String street, String town, String city, String country, String postCode)
        Address address = new Address(street, town, city, country, postCode);
        
        //public Delivery(DeliveryType type, DeliveryStatus status, CourierCompany courierCompany, Date predictedDeliveryDate, Order order, Address address)
        Delivery delivery = new Delivery(deliveryType, Delivery.DeliveryStatus.pending, new CourierCompany(), deliveryDate, loadedBasket , address);
        
        Checkout checkout = new Checkout(loadedUser, delivery.getOrder(),previousBasketFrame, loadedProduct, delivery);
        checkout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUsePreferredAddress;
    private javax.swing.JButton btnUseUserAddress;
    private javax.swing.JComboBox<String> cmboCourierCompany;
    private javax.swing.JComboBox<String> cmboDeliveryType;
    private javax.swing.JLabel lblCheckout;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblEstimatedDeliveryTime;
    private javax.swing.JLabel lblPostCode;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblTown;
    private javax.swing.JPanel pnlBanner2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtPostCode;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtTown;
    // End of variables declaration//GEN-END:variables
}
