package Views;

import Models.Magazine;
import Models.MagazineManager;
import Models.Order;
import Models.ProductManager;
import Models.ProductTag;
import Models.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucal
 */
public class HomePage extends javax.swing.JFrame {
    
    User loadedUser;
    Order loadedBasket;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        loadedUser = null;
        loadedBasket = null;
        loadHomePage();
        
        
    }
    
    public void loadHomePage()
    {
        if(loadedUser == null)
        {
            btnSignOut.setVisible(false);
        
        }
        else
        {
            btnLogin.setVisible(false);
            btnRegister.setVisible(false);
            
        }
        MagazineManager mManager = new MagazineManager();
        
        HashMap<Integer, Magazine> magazines = mManager.LoadMagazines();
        
        Magazine recentMagazine = new Magazine();
        recentMagazine.setDateCreated(new Date(Long.MIN_VALUE));
        
        for (Map.Entry<Integer, Magazine> entry : magazines.entrySet()) {
            if (entry.getValue().getDateCreated().after(recentMagazine.getDateCreated())) {
                recentMagazine = entry.getValue();
            }

        }

        lblMagazineTitle.setText(recentMagazine.getTitle());
        txtMagazineContent.setText(recentMagazine.getContent().substring(0, 55) + "...");

        ProductManager pManager = new ProductManager();
        HashMap<Integer, ProductTag> productTags = pManager.LoadProductTags();
        pnlCategories.setLayout(new BoxLayout(pnlCategories, BoxLayout.Y_AXIS));
        for (Map.Entry<Integer, ProductTag> entry : productTags.entrySet()) {
            ProductTag tag = entry.getValue();
            
            if (tag.getProductTagName().equals("Type")) {
                JButton button = new JButton(tag.getTagValue());
                button.setActionCommand(String.valueOf(tag.getProductTagId()));
                pnlCategories.add(button);

                button.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        List<Integer> ids = new ArrayList<>();
                        ids.add(tag.getProductTagId());
                        ChangePage(ids);
                        
                    }

                });
            }
            

        }
    }
    
    public void ChangePage(List<Integer> ids)
    {
        Products product = new Products(loadedUser, loadedBasket, ids, "");
        product.setVisible(true);
        this.dispose();
    }
    
    public HomePage(User user, Order order) {
        initComponents();
        loadedUser = user;
        loadedBasket = order;
        
        loadHomePage();
        
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblWelcomeText = new javax.swing.JLabel();
        pnlBanner = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnViewBasket1 = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMagazineTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMagazineContent = new javax.swing.JTextArea();
        btnReadFullMagazine = new javax.swing.JButton();
        scrlPnlCategories = new javax.swing.JScrollPane();
        pnlCategories = new javax.swing.JPanel();
        btnFAQ = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Products = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 81, -1, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 81, -1, -1));

        lblWelcomeText.setText("jLabel1");
        getContentPane().add(lblWelcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 156, -1, -1));

        pnlBanner.setBackground(new java.awt.Color(51, 204, 255));
        pnlBanner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        pnlBanner.setForeground(new java.awt.Color(102, 204, 255));
        pnlBanner.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("MaxiCycles");

        btnViewBasket1.setText("View Basket");
        btnViewBasket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBasket1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBannerLayout = new javax.swing.GroupLayout(pnlBanner);
        pnlBanner.setLayout(pnlBannerLayout);
        pnlBannerLayout.setHorizontalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnViewBasket1)
                .addGap(20, 20, 20))
        );
        pnlBannerLayout.setVerticalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBannerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnViewBasket1))
                .addGap(19, 19, 19))
        );

        getContentPane().add(pnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, -1, -1));

        btnSignOut.setText("Sign-Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 110, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Monthly Magazine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMagazineTitle.setText("MagazineTitle");

        txtMagazineContent.setEditable(false);
        txtMagazineContent.setColumns(20);
        txtMagazineContent.setLineWrap(true);
        txtMagazineContent.setRows(1);
        txtMagazineContent.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtMagazineContent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblMagazineTitle)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMagazineTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 270, 220, -1));

        btnReadFullMagazine.setText("Read Full Magazine");
        getContentPane().add(btnReadFullMagazine, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 241, -1, -1));

        scrlPnlCategories.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout pnlCategoriesLayout = new javax.swing.GroupLayout(pnlCategories);
        pnlCategories.setLayout(pnlCategoriesLayout);
        pnlCategoriesLayout.setHorizontalGroup(
            pnlCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        pnlCategoriesLayout.setVerticalGroup(
            pnlCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        scrlPnlCategories.setViewportView(pnlCategories);

        getContentPane().add(scrlPnlCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 241, 184, 140));

        btnFAQ.setText("FAQ");
        getContentPane().add(btnFAQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, -1, -1));

        jLabel4.setText("ProductCategories");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 215, -1, -1));

        Products.setText("Products");
        Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsActionPerformed(evt);
            }
        });
        getContentPane().add(Products, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 212, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        
        if(loadedUser == null){
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
        else if (loadedUser.getClass().getName().equals("Models.Customer"))
        {
            CustomerProfile customerProfile = new CustomerProfile(loadedUser,loadedBasket);
            customerProfile.setVisible(true);
            this.dispose();
        }
        else
        {
            StaffProfile staffProfile = new StaffProfile(loadedUser,loadedBasket);
            staffProfile.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsActionPerformed
        // TODO add your handling code here:
        
        Products products = new Products(loadedUser, loadedBasket, new ArrayList(), "");
        products.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductsActionPerformed

    private void btnViewBasket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBasket1ActionPerformed
        // TODO add your handling code here:

        Basket basket = new Basket(loadedUser,loadedBasket, "HomePage", null);
        basket.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewBasket1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Products;
    private javax.swing.JButton btnFAQ;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnReadFullMagazine;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnViewBasket1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMagazineTitle;
    private javax.swing.JLabel lblWelcomeText;
    private javax.swing.JPanel pnlBanner;
    private javax.swing.JPanel pnlCategories;
    private javax.swing.JScrollPane scrlPnlCategories;
    private javax.swing.JTextArea txtMagazineContent;
    // End of variables declaration//GEN-END:variables
}
