package Views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucal
 */

import Models.Order;
import Models.User;
import Models.UserManager;
import java.util.HashMap;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;



public class Login extends javax.swing.JFrame {

    
    Order basket;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblConfirmation = new javax.swing.JLabel();
        btnForgotPassword = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        psWrdPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setText("Login");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 6, -1, -1));

        lblUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 34, 74, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 102, -1, -1));

        lblConfirmation.setText("jLabel1");
        getContentPane().add(lblConfirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 146, -1, -1));

        btnForgotPassword.setText("Forgot Password");
        btnForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 143, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 178, -1, -1));
        getContentPane().add(psWrdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 74, 72, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsernameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        UserManager uManager = new UserManager();
        String username = lblUsername.getText();
        String password = String.copyValueOf(psWrdPassword.getPassword()) ;
        HashMap<String,User> users = uManager.LoadUsers();
        
        if(username.equals("") || password.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Fill All FIelds");
        }
        else if(!users.containsKey(username))
        {
            JOptionPane.showMessageDialog(rootPane, "No Existing Users With Input Username");
        }
        else
        {
            User user = uManager.logIn(username, password);
        
            if(user == null){
                JOptionPane.showMessageDialog(rootPane, "Incorrect Password");
            }
            else
            {
                lblConfirmation.setText("hello " + user.getFirstName());
                HomePage homePage = new HomePage(user, null);
                homePage.setVisible(true);
                this.dispose();
            }
        }

        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPasswordActionPerformed
        // TODO add your handling code here:
        
        UserManager uManager = new UserManager();
        HashMap<String,User> users = uManager.LoadUsers();
        String email = JOptionPane.showInputDialog("Please Enter Your Email");
        
        
        // TODO add your handling code here:
        String fromEmail = "joshuabh2021@googlemail.com";//studyviral2@gmail.com
        String FromEmailPassword = "Joshua230805";//You email Password from you want to send email
        String Subjects = "password reset code";
        Random random = new Random();
        int code = random.nextInt(10000);
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.starttls.enable","true");
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.put("mail.smtp.port","587");
        
        Session session = Session.getInstance(properties,new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(fromEmail, FromEmailPassword);
            }
        });
        
        try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(fromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(email));
            message.setSubject(Subjects);
            
            
            message.setText("Your password reset code is: " + code);
            Transport.send(message);
            
            
            
            
        }catch(Exception ex){
            System.out.println("Failed To Send Email"+ex);
        }
        
        try{
            
            int inputCode = Integer.parseInt(  JOptionPane.showInputDialog("a code has been emailed to you, Please Enter Code"));
            
            if(inputCode == code)
            {
                String newPassword = JOptionPane.showInputDialog("Please Enter Your New Password");
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Code Failed Please Try Again");
            System.out.println(""+ex);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btnForgotPasswordActionPerformed


    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        HomePage homePage = new HomePage(null, null);
        homePage.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnForgotPassword;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JTextField lblUsername;
    private javax.swing.JPasswordField psWrdPassword;
    // End of variables declaration//GEN-END:variables
}
