/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Delivery;
import Models.Order;
import Models.OrderManager;
import Models.Product;
import Models.ProductManager;
import Models.User;
import javax.swing.JOptionPane;

/**
 *
 * @author lucal
 */
public class PaymentPage extends javax.swing.JFrame {

    User loadedUser;
    Order loadedBasket;
    String lastFrame;
    Product loadedProduct;
    Delivery loadedDelivery;
    /**
     * Creates new form Payment
     */
    public PaymentPage(User user, Order order, String lastBasketFrame,Product product, Delivery delivery) {
        initComponents();
        loadedUser = user;
        loadedBasket = order;
        lastFrame = lastBasketFrame;
        loadedProduct = product;
        loadedDelivery = delivery;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner2 = new javax.swing.JPanel();
        lblPayment = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCardNumber = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        txtNameOnCard = new javax.swing.JTextField();
        lblNameOnCard = new javax.swing.JLabel();
        txtExpiryDate = new javax.swing.JTextField();
        lblExpiryDate = new javax.swing.JLabel();
        txtSecurityCode = new javax.swing.JTextField();
        lblSecurityCode = new javax.swing.JLabel();
        checkBoxSavePaymentInformation = new javax.swing.JCheckBox();
        checkBoxSavePaymentMethods = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        btnSendInvoice = new javax.swing.JButton();
        btnCashAmountPayed = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBanner2.setBackground(new java.awt.Color(51, 204, 255));
        pnlBanner2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        pnlBanner2.setForeground(new java.awt.Color(102, 204, 255));
        pnlBanner2.setToolTipText("");

        lblPayment.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPayment.setText("Payment");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner2Layout = new javax.swing.GroupLayout(pnlBanner2);
        pnlBanner2.setLayout(pnlBanner2Layout);
        pnlBanner2Layout.setHorizontalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(39, 39, 39))
        );
        pnlBanner2Layout.setVerticalGroup(
            pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBanner2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayment)
                    .addComponent(btnBack))
                .addGap(19, 19, 19))
        );

        lblCardNumber.setText("Card Number");

        lblNameOnCard.setText("Name On Card");

        lblExpiryDate.setText("ExpiryDate");

        lblSecurityCode.setText("Security Code");

        checkBoxSavePaymentInformation.setText("Save Payment Information");

        checkBoxSavePaymentMethods.setText("Save Payment Method");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnSendInvoice.setText("Send Invoice");

        btnCashAmountPayed.setText("Cash Amount Payed");

        lblPrice.setText("£400");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBanner2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(45, 45, 45)
                .addComponent(lblPrice)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCardNumber)
                            .addComponent(lblNameOnCard)
                            .addComponent(lblExpiryDate)
                            .addComponent(lblSecurityCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtSecurityCode, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameOnCard)
                            .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSendInvoice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCashAmountPayed)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxSavePaymentMethods)
                            .addComponent(checkBoxSavePaymentInformation))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBanner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardNumber)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameOnCard)
                    .addComponent(txtNameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpiryDate)
                    .addComponent(txtExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecurityCode)
                    .addComponent(txtSecurityCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxSavePaymentInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxSavePaymentMethods)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(btnSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendInvoice)
                    .addComponent(btnCashAmountPayed))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        Checkout checkout = new Checkout(loadedUser, loadedBasket, lastFrame,loadedProduct, null);
        checkout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
 
        OrderManager oManager = new OrderManager();
        ProductManager pManager = new ProductManager();
        
        oManager.RegisterDelivery(loadedDelivery);
        pManager.UpdateStockLevel(loadedBasket.getOrderLines());
        JOptionPane.showMessageDialog(rootPane, "Thank You For Your Purchase");
        HomePage homePage = new HomePage(loadedUser, null);
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCashAmountPayed;
    private javax.swing.JButton btnSendInvoice;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox checkBoxSavePaymentInformation;
    private javax.swing.JCheckBox checkBoxSavePaymentMethods;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblExpiryDate;
    private javax.swing.JLabel lblNameOnCard;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSecurityCode;
    private javax.swing.JPanel pnlBanner2;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtExpiryDate;
    private javax.swing.JTextField txtNameOnCard;
    private javax.swing.JTextField txtSecurityCode;
    // End of variables declaration//GEN-END:variables
}
