/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Order;
import Models.Product;
import Models.ProductManager;
import Models.User;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;

/**
 *
 * @author lucal
 */
public class Products extends javax.swing.JFrame {

    Order loadedBasket;
    User loadedUser;
    List<Integer> loadedTagIds;
    String loadedSearchString;
    /**
     * Creates new form Products
     */
    public Products(User user, Order order,  List<Integer> tagIds, String searchString ) {
        initComponents();
        loadedBasket = order;
        loadedUser = user;
        loadedUser = user;
        loadedTagIds = tagIds;
        pnlProductList.setLayout(new BoxLayout(pnlProductList, BoxLayout.Y_AXIS));

        
        ProductManager pManager = new ProductManager();
        HashMap<Integer, Product> products = pManager.LoadProductsByTag(tagIds);

        for (Map.Entry<Integer, Product> entry : products.entrySet()) {
            
            //creates jlabel for product icon
            JLabel lblIcon = new JLabel();
            //sets icon size
            lblIcon.setSize(210,210);
            //adds icon to product list panel
            pnlProductList.add(lblIcon);
            //creates jlabel for product name
            JLabel lblName = new JLabel();
            //sets lblname to produvct name
            lblName.setText(entry.getValue().getName());
            //creates new font using the font of lblname
            Font nameFont = lblName.getFont();
            //sets lblname font to bold and size 40
            lblName.setFont(nameFont.deriveFont(Font.BOLD, (float) 40));
            //adds lblname to product list panel
            pnlProductList.add(lblName);
            //creates label for product price
            JLabel lblPrice = new JLabel();
            //sets lblprice text to product price
            lblPrice.setText("£" + String.valueOf(entry.getValue().getPrice()));
            //creates new font use font of lblprice
            Font priceFont = lblPrice.getFont();
            //sets font of lblprice to have a font size of 25
            lblPrice.setFont(priceFont.deriveFont((float) 25));
            //adds lblprice to product list panel
            pnlProductList.add(lblPrice);

            try {
                //gets image file from product
                File imageFile = new File(entry.getValue().getImage());
                //creates biffered image and sets it as the selected file
                BufferedImage img = ImageIO.read(imageFile);
                //scales image to label icon
                Image scaledImg = img.getScaledInstance(lblIcon.getWidth(), lblIcon.getHeight(), Image.SCALE_SMOOTH);
                
                //sets label icon to image
                lblIcon.setIcon(new ImageIcon(scaledImg));
            } catch (Exception ex) {

                
                System.out.println("Unable to load product image:" + ex);
                lblIcon.setBorder(new LineBorder(Color.black));
            }
            
            JButton button = new JButton("View Product");
            button.setActionCommand(String.valueOf(entry.getValue().getProductId()) );
            pnlProductList.add(button);
            
            
            
            button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) 
            {
                int productId = Integer.parseInt(e.getActionCommand());
                openProductDetails(products.get(productId));                               
            }
                                                       
            });
        }
        
        
        
        
    }
    
    
    public void openProductDetails(Product product)
    {
        ProductDetails productDetails = new ProductDetails(loadedUser, product, loadedBasket, loadedTagIds, loadedSearchString);
        productDetails.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sclPnlProductList = new javax.swing.JScrollPane();
        pnlProductList = new javax.swing.JPanel();
        pnlBanner1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnViewBasket1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sclPnlProductList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sclPnlProductList.setToolTipText("");
        sclPnlProductList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlProductList.setLayout(new java.awt.GridLayout(1, 0));
        sclPnlProductList.setViewportView(pnlProductList);

        pnlBanner1.setBackground(new java.awt.Color(51, 204, 255));
        pnlBanner1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        pnlBanner1.setForeground(new java.awt.Color(102, 204, 255));
        pnlBanner1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Product Details");

        btnViewBasket1.setText("View Basket");
        btnViewBasket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBasket1ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBanner1Layout = new javax.swing.GroupLayout(pnlBanner1);
        pnlBanner1.setLayout(pnlBanner1Layout);
        pnlBanner1Layout.setHorizontalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanner1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewBasket1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(39, 39, 39))
        );
        pnlBanner1Layout.setVerticalGroup(
            pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBanner1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnViewBasket1)
                    .addComponent(btnBack))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sclPnlProductList, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBanner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sclPnlProductList, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewBasket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBasket1ActionPerformed
        // TODO add your handling code here:

        Basket basket = new Basket(loadedUser, loadedBasket, "Products", null);
        basket.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewBasket1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        HomePage homePage = new HomePage(loadedUser,loadedBasket);
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewBasket1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlBanner1;
    private javax.swing.JPanel pnlProductList;
    private javax.swing.JScrollPane sclPnlProductList;
    // End of variables declaration//GEN-END:variables
}
